services:
  - type: web
    name: atmos-weather-api
    region: ohio
    env: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
